openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /subtract:
    post:
      tags:
        - math-solution-controller
      operationId: subtract
      requestBody: JSON object with operand1 and operand2
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MathSolution'
        required: true
      responses: Answer is the difference of operand1 and operand2 (operand1 - operand2)
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolution'
  /multiply:
    post:
      tags:
        - math-solution-controller
      operationId: multiply
      requestBody: JSON object with operand1 and operand2
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MathSolution'
        required: true
      responses: Answer is the result of multiplying operand1 and operand2 (operand1 * operand2)
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolution'
  /divide:
    post:
      tags:
        - math-solution-controller
      operationId: divide
      requestBody:  JSON object with operand1 and operand2
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MathSolution'
        required: true
      responses:  Answer is the result of dividing operand1 and operand2 (operand1 / operand2)
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolution'
  /add:
    post:
      tags:
        - math-solution-controller
      operationId: add
      requestBody: JSON object with operand1 and operand2
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MathSolution'
        required: true
      responses:  Answer is the result of adding operand1 and operand2 (operand1 + operand2)
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolution'
  /month/{monthNumber}:
    get:
      tags:
        - month-controller
      operationId: getMonth
      parameters:
        - name: monthNumber
          in: path
          required: true
          schema:
            type: string
      responses: Response should be a string with the name of the month corresponding to the valid integer input of 1 through 12.
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    MathSolution:
      type: object
      properties:
        operand1:
          type: integer
          format: int32
        operand2:
          type: integer
          format: int32
        operation:
          type: string
        answer:
          type: integer
          format: int32
